### ISSUE TITLE
Deleting a block group

### ISSUE THREAD

**Issue by VladislavAksiotis** [andreasxp/nfb_studio#2]
When I created an empty group of block and clicked to delete it, I received the following:

```
Traceback (most recent call last):
  File "c:\users\владислав\nfb_studio\nfb_studio\property_tree\view.py", line 70, in <lambda>
    delete.triggered.connect(lambda: model.removeBlock(item.text()))
  File "c:\users\владислав\nfb_studio\nfb_studio\property_tree\model.py", line 89, in removeBlock
    ex.blocks.pop(name)
  File "D:\Conda3\envs\nfb_studio\lib\_collections_abc.py", line 819, in pop
    value = self[key]
  File "c:\users\владислав\nfb_studio\nfb_studio\item_dict.py", line 45, in __getitem__
    return self._data.__getitem__(key)
KeyError: 'Group1'
```

There were two existed blocks, but the group was empty. It wasn't imported experiment, I have created it in NFB Studio.
UPD: deleting doesn't work in any experiment setting

**Comment by andreasxp** [comment]
Fixed in master.
